apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-v1
  labels:
    version: v1
    app: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        version: v1
        app: billing
    spec:
      containers:
        - name: billing
          image: claudioed/tracking:no-redirect
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 500Mi
          env:
            - name: SERVICE_NAME
              value: billing
            - name: SERVICE_VERSION
              value: v1
            - name: TARGET_SERVICE_HOST
              value: https://httpbin.org/get
          ports:
            - containerPort: 8080
          securityContext:
            privileged: false
          livenessProbe:
            httpGet:
              path: /billing/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
          readinessProbe:
            httpGet:
              path: /billing/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: billing
  labels:
    expose: "true"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: billing