apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-v1
  labels:
    version: v1
    app: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        version: v1
        app: router
    spec:
      containers:
        - name: router
          image: claudioed/tracking
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 500Mi
          env:
            - name: SERVICE_NAME
              value: router
            - name: SERVICE_VERSION
              value: v1
            - name: TARGET_SERVICE_HOST
              value: http://price:8080/price
          ports:
            - containerPort: 8080
          securityContext:
            privileged: false
          livenessProbe:
            httpGet:
              path: /router/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
          readinessProbe:
            httpGet:
              path: /router/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    expose: "true"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: router