apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "book-api-auth-policy"
spec:
  targets:
    - name: book
  origins:
    - jwt:
        audiences:
          - book
        issuer: "http://35.238.13.155/auth/realms/library"
        jwksUri: "http://35.238.13.155/auth/realms/library/protocol/openid-connect/certs"
        trigger_rules:
          - excluded_paths:
              - exact: /book/health
  principalBinding: USE_ORIGIN