apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "c4-active-api-auth-policy"
spec:
  targets:
    - name: c4-active
  origins:
    - jwt:
        audiences:
          - book
        issuer: "http://35.238.13.155/auth/realms/library"
        jwksUri: "http://35.238.13.155/auth/realms/library/protocol/openid-connect/certs"
  principalBinding: USE_ORIGIN