apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-v2
  labels:
    version: v2
    app: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        version: v2
        app: billing
    spec:
      containers:
        - name: billing
          image: claudioed/tracking:no-redirect
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 500Mi
          env:
            - name: SERVICE_NAME
              value: billing
            - name: SERVICE_VERSION
              value: v2
          ports:
            - containerPort: 8080
          securityContext:
            privileged: false
          livenessProbe:
            httpGet:
              path: /billing/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
          readinessProbe:
            httpGet:
              path: /billing/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1