apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-v2
  labels:
    version: v2
    app: ride
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride
  template:
    metadata:
      labels:
        version: v2
        app: ride
    spec:
      containers:
        - name: ride
          image: claudioed/tracking
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 500Mi
          env:
            - name: SERVICE_NAME
              value: ride
            - name: SERVICE_VERSION
              value: v2
            - name: TARGET_SERVICE_HOST
              value: http://driver:8080/driver
          ports:
            - containerPort: 8080
          securityContext:
            privileged: false
          livenessProbe:
            httpGet:
              path: /ride/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
          readinessProbe:
            httpGet:
              path: /ride/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1